{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GeometryType_MultiPolygon"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GeometryType","preciseIdentifier":"c:@EA@MBXGeometryType","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeometryType"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"variants":[{"paths":["\/documentation\/mapboxcommon\/geometrytype_multipolygon"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/geometrytype_multipolygon"]}],"metadata":{"modules":[{"name":"MapboxCommon"}],"roleHeading":"Global Variable","symbolKind":"var","externalID":"c:@EA@MBXGeometryType@MBXGeometryType_MultiPolygon","navigatorTitle":[{"kind":"identifier","text":"MBXGeometryType_MultiPolygon"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GeometryType_MultiPolygon","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@EA@MBXGeometryType","kind":"typeIdentifier","text":"GeometryType"}],"title":"GeometryType_MultiPolygon"},"kind":"symbol","sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeometryType_MultiPolygon"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon"],["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TurfAPI","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeometryType"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","title":"MapboxCommon","url":"\/documentation\/mapboxcommon","abstract":[],"role":"collection","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","type":"topic","kind":"article","abstract":[],"url":"\/documentation\/overview","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"kind":"symbol","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"title":"MapboxMaps","type":"topic","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/GeometryType":{"abstract":[],"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GeometryType","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/geometrytype","title":"GeometryType","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeometryType","navigatorTitle":[{"kind":"identifier","text":"GeometryType"}],"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/GeometryType_MultiPolygon":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"GeometryType_MultiPolygon","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@EA@MBXGeometryType","text":"GeometryType","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/GeometryType_MultiPolygon","abstract":[],"role":"symbol","url":"\/documentation\/mapboxcommon\/geometrytype_multipolygon","type":"topic","navigatorTitle":[{"text":"MBXGeometryType_MultiPolygon","kind":"identifier"}],"kind":"symbol","title":"GeometryType_MultiPolygon"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TurfAPI":{"url":"\/documentation\/mapboxmaps\/turfapi","title":"Turf","role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TurfAPI","kind":"article","type":"topic","abstract":[{"text":"Describes ","type":"text"},{"code":"turf-swift","type":"codeVoice"},{"type":"text","text":" dependency objects"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"MBXGeometryType_MultiPolygon"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"MBXGeometryType_MultiPolygon","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"identifier","text":"MBXGeometryType_MultiPolygon"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"MBXGeometryType","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1GeometryType\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1GeometryType\/fragments","value":[{"text":"","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"MBXGeometryType"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1GeometryType\/navigatorTitle"},{"value":"MBXGeometryType_MultiPolygon","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1GeometryType_MultiPolygon\/title"},{"value":[{"kind":"identifier","text":"MBXGeometryType_MultiPolygon"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1GeometryType_MultiPolygon\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}