{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Settings-and-Constants"]]},"topicSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MapboxOptions\/accessToken"],"title":"Type Properties","generated":true,"anchor":"Type-Properties"}],"metadata":{"symbolKind":"class","roleHeading":"Class","externalID":"c:objc(cs)MBXMapboxOptions","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MapboxOptions"}],"navigatorTitle":[{"text":"MapboxOptions","kind":"identifier"}],"modules":[{"name":"MapboxCommon"}],"title":"MapboxOptions","role":"symbol"},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MapboxOptions","interfaceLanguage":"swift"},"sections":[],"seeAlsoSections":[{"generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MapboxCommonSettings","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMapsOptions"],"title":"Settings","anchor":"Settings"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MapboxOptions"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/mapboxcommon\/mapboxoptions"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxcommon\/mapboxoptions"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"type":"inheritsFrom"},{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","abstract":[{"type":"text","text":"Class for Mapbox SDK settings management"}],"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","type":"topic","kind":"article","abstract":[],"url":"\/documentation\/overview","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection"},"doc://com.mapbox.MapboxMaps/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ"},"doc://com.mapbox.MapboxMaps/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP"},"doc://com.mapbox.MapboxMaps/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/MBXMapboxOptions/setAccessTokenForToken:":{"title":"setAccessTokenForToken:","type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXMapboxOptions\/setAccessTokenForToken:","url":"\/documentation\/mapboxcommon\/mbxmapboxoptions\/setaccesstokenfortoken:","navigatorTitle":[{"text":"setAccessTokenForToken:","kind":"identifier"}],"fragments":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"setAccessTokenForToken:"}],"role":"symbol","abstract":[{"type":"text","text":"Set access token to be used by all Mapbox SDK."}]},"doc://com.mapbox.MapboxMaps/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/MapboxOptions/accessToken":{"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MapboxOptions\/accessToken","title":"accessToken","url":"\/documentation\/mapboxcommon\/mapboxoptions\/accesstoken","abstract":[{"type":"text","text":"Access token to be used by all the Mapbox SDKs."}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessToken"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/MBXMapboxOptions/getAccessToken":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"getAccessToken"}],"abstract":[{"text":"Get Mapbox access token.","type":"text"}],"title":"getAccessToken","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getAccessToken"}],"url":"\/documentation\/mapboxcommon\/mbxmapboxoptions\/getaccesstoken","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXMapboxOptions\/getAccessToken","kind":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapboxMapsOptions":{"role":"symbol","abstract":[{"type":"text","text":"Configurations for the external resources that are used by Maps API object,"},{"text":" ","type":"text"},{"type":"text","text":"such as maps data directory and base URL."}],"url":"\/documentation\/mapboxmaps\/mapboxmapsoptions","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MapboxMapsOptions"}],"navigatorTitle":[{"text":"MapboxMapsOptions","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapboxMapsOptions","type":"topic","kind":"symbol","title":"MapboxMapsOptions"},"doc://com.mapbox.MapboxMaps/SH":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"kind":"symbol","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"title":"MapboxMaps","type":"topic","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Settings-and-Constants":{"role":"collectionGroup","type":"topic","url":"\/documentation\/mapboxmaps\/settings-and-constants","title":"Settings and Constants","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Settings-and-Constants","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/MapboxOptions":{"url":"\/documentation\/mapboxcommon\/mapboxoptions","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MapboxOptions","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MapboxOptions","title":"MapboxOptions","type":"topic","navigatorTitle":[{"text":"MapboxOptions","kind":"identifier"}],"abstract":[{"type":"text","text":"Class for Mapbox SDK settings management"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/MapboxCommonSettings":{"kind":"symbol","abstract":[{"type":"text","text":"Set of common keys that can be used to configure all Mapbox SDKs."}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MapboxCommonSettings"}],"title":"MapboxCommonSettings","navigatorTitle":[{"text":"MapboxCommonSettings","kind":"identifier"}],"role":"symbol","url":"\/documentation\/mapboxcommon\/mapboxcommonsettings","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MapboxCommonSettings"},"doc://com.mapbox.MapboxMaps/objc(pl)NSObject":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/objc(cs)NSObject":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"MBXMapboxOptions","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"MBXMapboxOptions","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBXMapboxOptions"}]},{"value":[{"anchor":"Type-Methods","title":"Type Methods","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXMapboxOptions\/getAccessToken","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MBXMapboxOptions\/setAccessTokenForToken:"]}],"path":"\/topicSections","op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"type":"inheritsFrom"}]},{"path":"\/seeAlsoSections","value":[{"title":"Settings","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/MapboxCommonSettings"],"generated":true,"anchor":"Settings"}],"op":"replace"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MBXMapboxOptions"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1MapboxOptions\/title","value":"MBXMapboxOptions","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1MapboxOptions\/fragments","value":[{"text":"MBXMapboxOptions","kind":"identifier"}]},{"op":"replace","value":[{"text":"MBXMapboxOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1MapboxOptions\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1MapboxCommonSettings\/title","value":"MBXMapboxCommonSettings"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1MapboxCommonSettings\/fragments","value":[{"kind":"identifier","text":"MBXMapboxCommonSettings"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1MapboxCommonSettings\/navigatorTitle","value":[{"text":"MBXMapboxCommonSettings","kind":"identifier"}]}]}]}