{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layers","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerHost"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/customlayerhost\/renderingwillstartopengl()"]},{"paths":["\/documentation\/mapboxmaps\/customlayerhost\/renderingwillstartopengl()"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Instance Method","role":"symbol","symbolKind":"method","navigatorTitle":[{"text":"renderingWillStartOpenGL","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"renderingWillStartOpenGL"},{"text":"()","kind":"text"}],"modules":[{"name":"MapboxMaps"}],"externalID":"c:objc(pl)MBMCustomLayerHost(im)renderingWillStartOpenGL","title":"renderingWillStartOpenGL()"},"abstract":[{"text":"Initialize any OpenGL 3D graphic API state needed by the custom layer. This method is called","type":"text"},{"type":"text","text":" "},{"text":"once when view starts or resumes to foreground but before rendering for the first time.","type":"text"}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerHost\/renderingWillStartOpenGL()","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"renderingWillStartOpenGL"},{"kind":"text","text":"()"}]}]},{"content":[{"level":2,"anchor":"discussion","text":"Discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"As Apple is deprecating legacy OpenGL API, this method is optional and is called only if"},{"type":"text","text":" "},{"type":"text","text":"underlying map rendering backend uses OpenGL graphic API."}]},{"inlineContent":[{"text":"Resources that are acquired in this method must be released in the ","type":"text"},{"type":"codeVoice","code":"deinitialize"},{"text":" function.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Layers":{"type":"topic","title":"Layers","kind":"article","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Layers","role":"collectionGroup","url":"\/documentation\/mapboxmaps\/layers"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerHost/renderingWillStartOpenGL()":{"url":"\/documentation\/mapboxmaps\/customlayerhost\/renderingwillstartopengl()","role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"renderingWillStartOpenGL","kind":"identifier"},{"text":"()","kind":"text"}],"abstract":[{"type":"text","text":"Initialize any OpenGL 3D graphic API state needed by the custom layer. This method is called"},{"type":"text","text":" "},{"text":"once when view starts or resumes to foreground but before rendering for the first time.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"renderingWillStartOpenGL"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerHost\/renderingWillStartOpenGL()","title":"renderingWillStartOpenGL()"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"kind":"symbol","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"title":"MapboxMaps","type":"topic","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomLayerHost":{"url":"\/documentation\/mapboxmaps\/customlayerhost","title":"CustomLayerHost","abstract":[{"text":"Interface for hosting a custom map style layer.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CustomLayerHost"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomLayerHost","navigatorTitle":[{"text":"CustomLayerHost","kind":"identifier"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","type":"topic","kind":"article","abstract":[],"url":"\/documentation\/overview","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"renderingWillStartOpenGL","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"renderingWillStartOpenGL"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"renderingWillStartOpenGL"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"renderingWillStartOpenGL","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerHost~1renderingWillStartOpenGL()\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"renderingWillStartOpenGL","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerHost~1renderingWillStartOpenGL()\/fragments"},{"value":"MBMCustomLayerHost","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerHost\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerHost\/fragments","value":[{"text":"MBMCustomLayerHost","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomLayerHost\/navigatorTitle","value":[{"kind":"identifier","text":"MBMCustomLayerHost"}]}]}]}