{"seeAlsoSections":[{"generated":true,"title":"Sources","anchor":"Sources","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Source","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceInfo","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GeoJSONSource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GeoJSONSourceData","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ImageSource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterSource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterArraySource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/VectorSource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PromoteId","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Scheme","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Encoding","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySourceOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatusChangedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileData","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatus","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClient","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileRenderer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClientType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileFunctionCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetSize"]}],"abstract":[{"type":"text","text":"Options for custom raster source."}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Sources"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceOptions"},"sections":[],"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"title":"Inherits From"},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject","doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomRasterSourceOptions","kind":"identifier"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/customrastersourceoptions"]},{"paths":["\/documentation\/mapboxmaps\/customrastersourceoptions"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","symbolKind":"class","roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"CustomRasterSourceOptions"}],"externalID":"c:objc(cs)MBMCustomRasterSourceOptions","modules":[{"name":"MapboxMaps"}],"title":"CustomRasterSourceOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"CustomRasterSourceOptions","kind":"identifier"}]},"topicSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceOptions\/init(clientCallback:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceOptions\/init(clientCallback:minZoom:maxZoom:tileSize:)"],"anchor":"Initializers","generated":true,"title":"Initializers"},{"generated":true,"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceOptions\/clientCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceOptions\/maxZoom","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceOptions\/minZoom","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceOptions\/tileSize"]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceClientType":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClientType","role":"symbol","url":"\/documentation\/mapboxmaps\/customrastersourceclienttype","abstract":[],"navigatorTitle":[{"text":"CustomRasterSourceClientType","kind":"identifier"}],"type":"topic","title":"CustomRasterSourceClientType","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomRasterSourceClientType"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterArraySource":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterArraySource","abstract":[{"text":"A raster array source","type":"text"}],"navigatorTitle":[{"text":"RasterArraySource","kind":"identifier"}],"tags":[{"text":"SPI","type":"spi"}],"kind":"symbol","role":"symbol","url":"\/documentation\/mapboxmaps\/rasterarraysource","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RasterArraySource"}],"title":"RasterArraySource"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterDemSource":{"type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"RasterDemSource"}],"title":"RasterDemSource","navigatorTitle":[{"text":"RasterDemSource","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/rasterdemsource","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource","abstract":[{"type":"text","text":"A RGB-encoded raster DEM source"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceOptions/maxZoom":{"type":"topic","url":"\/documentation\/mapboxmaps\/customrastersourceoptions\/maxzoom","title":"maxZoom","role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"maxZoom"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5UInt8V","text":"UInt8"}],"navigatorTitle":[{"kind":"identifier","text":"maxZoom"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceOptions\/maxZoom","abstract":[{"text":"A maximum zoom level, at which to create vector tiles.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceTileStatus":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatus","role":"symbol","url":"\/documentation\/mapboxmaps\/customrastersourcetilestatus","abstract":[{"type":"text","text":"CustomRasterSource tile status."}],"navigatorTitle":[{"kind":"identifier","text":"CustomRasterSourceTileStatus"}],"type":"topic","title":"CustomRasterSourceTileStatus","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomRasterSourceTileStatus"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"kind":"symbol","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"title":"MapboxMaps","type":"topic","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/VectorSource":{"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VectorSource","kind":"identifier"}],"kind":"symbol","title":"VectorSource","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/VectorSource","abstract":[{"text":"A vector tile source.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"VectorSource"}],"type":"topic","url":"\/documentation\/mapboxmaps\/vectorsource"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceOptions/clientCallback":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceOptions\/clientCallback","role":"symbol","navigatorTitle":[{"text":"clientCallback","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"The client callback.","type":"text"}],"title":"clientCallback","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"clientCallback","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMCustomRasterSourceClient","text":"CustomRasterSourceClient","kind":"typeIdentifier"}],"url":"\/documentation\/mapboxmaps\/customrastersourceoptions\/clientcallback"},"doc://com.mapbox.MapboxMaps/objc(cs)NSObject":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/SH":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceOptions/tileSize":{"abstract":[{"text":"Size of the tiles. Tile size must be a power of 2. Default is ","type":"text"},{"code":"512","type":"codeVoice"},{"type":"text","text":"."}],"navigatorTitle":[{"kind":"identifier","text":"tileSize"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceOptions\/tileSize","url":"\/documentation\/mapboxmaps\/customrastersourceoptions\/tilesize","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tileSize","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt16","kind":"typeIdentifier","preciseIdentifier":"s:s6UInt16V"}],"title":"tileSize"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceOptions/init(clientCallback:)":{"kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/customrastersourceoptions\/init(clientcallback:)","navigatorTitle":[{"kind":"identifier","text":"initWithClientCallback:"}],"abstract":[],"title":"init(clientCallback:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"clientCallback","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CustomRasterSourceClient","preciseIdentifier":"c:objc(cs)MBMCustomRasterSourceClient"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceOptions\/init(clientCallback:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterSource":{"abstract":[{"text":"A raster tile source.","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/rastersource","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterSource","role":"symbol","title":"RasterSource","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RasterSource"}],"navigatorTitle":[{"text":"RasterSource","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceInfo":{"type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SourceInfo"}],"title":"SourceInfo","navigatorTitle":[{"kind":"identifier","text":"SourceInfo"}],"url":"\/documentation\/mapboxmaps\/sourceinfo","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceInfo","abstract":[{"type":"text","text":"Information about a Source"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceOptions/init(clientCallback:minZoom:maxZoom:tileSize:)":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceOptions\/init(clientCallback:minZoom:maxZoom:tileSize:)","role":"symbol","navigatorTitle":[{"text":"initWithClientCallback:minZoom:maxZoom:tileSize:","kind":"identifier"}],"kind":"symbol","abstract":[],"title":"init(clientCallback:minZoom:maxZoom:tileSize:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"clientCallback"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)MBMCustomRasterSourceClient","text":"CustomRasterSourceClient","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"minZoom"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5UInt8V","kind":"typeIdentifier","text":"UInt8"},{"text":", ","kind":"text"},{"text":"maxZoom","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5UInt8V","text":"UInt8","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"tileSize"},{"kind":"text","text":": "},{"text":"UInt16","preciseIdentifier":"s:s6UInt16V","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/mapboxmaps\/customrastersourceoptions\/init(clientcallback:minzoom:maxzoom:tilesize:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomGeometrySource":{"type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomGeometrySource"}],"title":"CustomGeometrySource","navigatorTitle":[{"kind":"identifier","text":"CustomGeometrySource"}],"url":"\/documentation\/mapboxmaps\/customgeometrysource","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySource","abstract":[{"type":"text","text":"Describes a Custom Geometry Source to be used in the style"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceClient":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClient","role":"symbol","url":"\/documentation\/mapboxmaps\/customrastersourceclient","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"CustomRasterSourceClient"}],"type":"topic","title":"CustomRasterSourceClient","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomRasterSourceClient"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ImageSource":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ImageSource","role":"symbol","url":"\/documentation\/mapboxmaps\/imagesource","abstract":[{"type":"text","text":"An image data source."}],"navigatorTitle":[{"kind":"identifier","text":"ImageSource"}],"type":"topic","title":"ImageSource","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ImageSource"}]},"doc://com.mapbox.MapboxMaps/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/objc(pl)NSObject"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Scheme":{"type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"Scheme","kind":"identifier"}],"title":"Scheme","navigatorTitle":[{"kind":"identifier","text":"Scheme"}],"url":"\/documentation\/mapboxmaps\/scheme","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Scheme","abstract":[{"text":"Influences the y direction of the tile coordinates. The global-mercator (aka Spherical Mercator) profile is assumed.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceOptions/minZoom":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceOptions\/minZoom","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"minZoom"}],"kind":"symbol","abstract":[{"type":"text","text":"A minimum zoom level, at which to create vector tiles."}],"title":"minZoom","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"minZoom"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5UInt8V","text":"UInt8","kind":"typeIdentifier"}],"url":"\/documentation\/mapboxmaps\/customrastersourceoptions\/minzoom"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PromoteId":{"abstract":[],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PromoteId","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/promoteid","type":"topic","role":"symbol","title":"PromoteId","navigatorTitle":[{"text":"PromoteId","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PromoteId"},"doc://com.mapbox.MapboxMaps/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GeoJSONSourceData":{"type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"GeoJSONSourceData"}],"title":"GeoJSONSourceData","navigatorTitle":[{"kind":"identifier","text":"GeoJSONSourceData"}],"url":"\/documentation\/mapboxmaps\/geojsonsourcedata","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GeoJSONSourceData","abstract":[{"type":"text","text":"Captures potential values of the "},{"code":"data","type":"codeVoice"},{"type":"text","text":" property of a GeoJSONSource."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceTileRenderer":{"type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"CustomRasterSourceTileRenderer","kind":"identifier"}],"title":"CustomRasterSourceTileRenderer","navigatorTitle":[{"kind":"identifier","text":"CustomRasterSourceTileRenderer"}],"url":"\/documentation\/mapboxmaps\/customrastersourcetilerenderer","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileRenderer","abstract":[{"text":"Interface for the direct rendering into the custom raster tiles.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","type":"topic","kind":"article","abstract":[],"url":"\/documentation\/overview","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomGeometrySourceOptions":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySourceOptions","role":"symbol","url":"\/documentation\/mapboxmaps\/customgeometrysourceoptions","abstract":[{"type":"text","text":"Options for custom geometry source."}],"navigatorTitle":[{"text":"CustomGeometrySourceOptions","kind":"identifier"}],"type":"topic","title":"CustomGeometrySourceOptions","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomGeometrySourceOptions"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceOptions":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceOptions","role":"symbol","url":"\/documentation\/mapboxmaps\/customrastersourceoptions","abstract":[{"text":"Options for custom raster source.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"CustomRasterSourceOptions"}],"type":"topic","title":"CustomRasterSourceOptions","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CustomRasterSourceOptions"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceTileData":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileData","role":"symbol","url":"\/documentation\/mapboxmaps\/customrastersourcetiledata","abstract":[{"type":"text","text":"Data for a specific CustomRasterSource tile."}],"navigatorTitle":[{"kind":"identifier","text":"CustomRasterSourceTileData"}],"type":"topic","title":"CustomRasterSourceTileData","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomRasterSourceTileData"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Encoding":{"type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Encoding"}],"title":"Encoding","navigatorTitle":[{"kind":"identifier","text":"Encoding"}],"url":"\/documentation\/mapboxmaps\/encoding","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Encoding","abstract":[{"type":"text","text":"The encoding used by this source. Mapbox Terrain RGB is used by default"}]},"doc://com.mapbox.MapboxMaps/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s7CVarArgP","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCacheBudgetSize":{"role":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetSize","url":"\/documentation\/mapboxmaps\/tilecachebudgetsize","abstract":[{"type":"text","text":"Defines a TileCacheBudgetSize, which can be set as either a megabyte or tile count limit."},{"type":"text","text":" "},{"text":"Whenever tile cache goes over the defined limit","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"the least recently used tile will be evicted from the in-memory cache"}],"title":"TileCacheBudgetSize","navigatorTitle":[{"kind":"identifier","text":"TileCacheBudgetSize"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TileCacheBudgetSize"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceTileStatusChangedCallback":{"type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CustomRasterSourceTileStatusChangedCallback"}],"title":"CustomRasterSourceTileStatusChangedCallback","navigatorTitle":[{"kind":"identifier","text":"CustomRasterSourceTileStatusChangedCallback"}],"url":"\/documentation\/mapboxmaps\/customrastersourcetilestatuschangedcallback","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatusChangedCallback","abstract":[{"type":"text","text":"Callback for changing a CustomRasterSource tile status."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileFunctionCallback":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileFunctionCallback","role":"symbol","url":"\/documentation\/mapboxmaps\/tilefunctioncallback","abstract":[{"type":"text","text":"Callback to do various operations for tile."},{"type":"text","text":" "},{"type":"text","text":"For example, fetching a tile or cancelling a tile request."}],"navigatorTitle":[{"kind":"identifier","text":"TileFunctionCallback"}],"type":"topic","title":"TileFunctionCallback","kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileFunctionCallback"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSource":{"type":"topic","role":"symbol","tags":[{"type":"spi","text":"SPI"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"CustomRasterSource","kind":"identifier"}],"title":"CustomRasterSource","navigatorTitle":[{"kind":"identifier","text":"CustomRasterSource"}],"url":"\/documentation\/mapboxmaps\/customrastersource","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSource","abstract":[{"type":"text","text":"Describes a Custom Raster Source to be used in the style."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Sources":{"abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Sources","role":"collectionGroup","kind":"article","type":"topic","url":"\/documentation\/mapboxmaps\/sources","title":"Sources"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceType":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceType","role":"symbol","url":"\/documentation\/mapboxmaps\/sourcetype","abstract":[{"text":"Struct of supported Source Types","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Docs : https:\/\/docs.mapbox.com\/mapbox-gl-js\/style-spec\/sources\/"}],"navigatorTitle":[{"kind":"identifier","text":"SourceType"}],"type":"topic","title":"SourceType","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SourceType"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Source":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Source","role":"symbol","url":"\/documentation\/mapboxmaps\/source","abstract":[],"navigatorTitle":[{"text":"Source","kind":"identifier"}],"type":"topic","title":"Source","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Source"}]},"doc://com.mapbox.MapboxMaps/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GeoJSONSource":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GeoJSONSource"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"GeoJSONSource","kind":"identifier"}],"abstract":[{"type":"text","text":"A GeoJSON data source."}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GeoJSONSource","kind":"symbol","title":"GeoJSONSource","url":"\/documentation\/mapboxmaps\/geojsonsource"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","value":"MBMCustomRasterSourceOptions","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"path":"\/metadata\/fragments","value":[{"text":"MBMCustomRasterSourceOptions","kind":"identifier"}],"op":"replace"},{"value":[{"text":"MBMCustomRasterSourceOptions","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceOptions\/clientCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceOptions\/maxZoom","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceOptions\/minZoom","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceOptions\/tileSize"]},{"title":"Instance Methods","generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceOptions\/init(clientCallback:)","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceOptions\/init(clientCallback:minZoom:maxZoom:tileSize:)"]}],"op":"replace","path":"\/topicSections"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"}],"path":"\/relationshipsSections"},{"value":[{"title":"Sources","anchor":"Sources","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySourceOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatusChangedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileData","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatus","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClient","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileRenderer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClientType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileFunctionCallback"]}],"op":"replace","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MBMCustomRasterSourceOptions"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClientType\/title","op":"replace","value":"MBMCustomRasterSourceClientType"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClientType\/fragments","value":[{"kind":"identifier","text":"MBMCustomRasterSourceClientType"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClientType\/navigatorTitle","op":"replace","value":[{"text":"MBMCustomRasterSourceClientType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions~1maxZoom\/title","value":"maxZoom","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions~1maxZoom\/fragments","value":[{"text":"maxZoom","kind":"identifier"}],"op":"replace"},{"value":"MBMCustomRasterSourceTileStatus","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatus\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatus\/fragments","value":[{"kind":"identifier","text":"MBMCustomRasterSourceTileStatus"}]},{"value":[{"kind":"identifier","text":"MBMCustomRasterSourceTileStatus"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatus\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions~1clientCallback\/title","op":"replace","value":"clientCallback"},{"op":"replace","value":[{"text":"clientCallback","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions~1clientCallback\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions~1tileSize\/title","op":"replace","value":"tileSize"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions~1tileSize\/fragments","value":[{"text":"tileSize","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions~1init(clientCallback:)\/title","value":"initWithClientCallback:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions~1init(clientCallback:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithClientCallback:","kind":"identifier"}]},{"value":"initWithClientCallback:minZoom:maxZoom:tileSize:","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions~1init(clientCallback:minZoom:maxZoom:tileSize:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions~1init(clientCallback:minZoom:maxZoom:tileSize:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithClientCallback:minZoom:maxZoom:tileSize:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClient\/title","value":"MBMCustomRasterSourceClient"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClient\/fragments","value":[{"text":"MBMCustomRasterSourceClient","kind":"identifier"}]},{"value":[{"text":"MBMCustomRasterSourceClient","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClient\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions~1minZoom\/title","value":"minZoom"},{"op":"replace","value":[{"text":"minZoom","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions~1minZoom\/fragments"},{"op":"replace","value":"MBMCustomRasterSourceTileRenderer","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileRenderer\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MBMCustomRasterSourceTileRenderer"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileRenderer\/fragments"},{"op":"replace","value":[{"text":"MBMCustomRasterSourceTileRenderer","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileRenderer\/navigatorTitle"},{"op":"replace","value":"MBMCustomGeometrySourceOptions","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomGeometrySourceOptions\/title"},{"op":"replace","value":[{"text":"MBMCustomGeometrySourceOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomGeometrySourceOptions\/fragments"},{"value":[{"text":"MBMCustomGeometrySourceOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomGeometrySourceOptions\/navigatorTitle","op":"replace"},{"op":"replace","value":"MBMCustomRasterSourceOptions","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions\/title"},{"op":"replace","value":[{"text":"MBMCustomRasterSourceOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions\/navigatorTitle","value":[{"text":"MBMCustomRasterSourceOptions","kind":"identifier"}],"op":"replace"},{"value":"MBMCustomRasterSourceTileData","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileData\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileData\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMCustomRasterSourceTileData"}]},{"op":"replace","value":[{"text":"MBMCustomRasterSourceTileData","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileData\/navigatorTitle"},{"value":"MBMCustomRasterSourceTileStatusChangedCallback","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatusChangedCallback\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatusChangedCallback\/fragments","value":[{"text":"MBMCustomRasterSourceTileStatusChangedCallback","kind":"identifier"}],"op":"replace"},{"value":[{"text":"MBMCustomRasterSourceTileStatusChangedCallback","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatusChangedCallback\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileFunctionCallback\/title","value":"MBMTileFunctionCallback","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileFunctionCallback\/fragments","value":[{"kind":"identifier","text":"MBMTileFunctionCallback"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileFunctionCallback\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMTileFunctionCallback"}]}]}]}