{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"line","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"locations","kind":"internalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"NSValue","preciseIdentifier":"c:objc(cs)NSValue"},{"text":"])","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/geometry\/init(line:)"]},{"paths":["\/documentation\/mapboxcommon\/geometry\/init(line:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry"]]},"kind":"symbol","metadata":{"modules":[{"name":"MapboxCommon"}],"roleHeading":"Initializer","symbolKind":"init","externalID":"c:objc(cs)MBXGeometry(im)initWithLine:","navigatorTitle":[{"text":"initWithLine:","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"line"},{"text":": [","kind":"text"},{"text":"NSValue","preciseIdentifier":"c:objc(cs)NSValue","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"title":"init(line:)"},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry\/init(line:)","interfaceLanguage":"swift"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Geometry":{"role":"symbol","kind":"symbol","title":"Geometry","navigatorTitle":[{"text":"Geometry","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Geometry"}],"type":"topic","url":"\/documentation\/mapboxcommon\/geometry"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","title":"MapboxCommon","url":"\/documentation\/mapboxcommon","abstract":[],"role":"collection","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","type":"topic","kind":"article","abstract":[],"url":"\/documentation\/overview","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Geometry/init(line:)":{"role":"symbol","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry\/init(line:)","url":"\/documentation\/mapboxcommon\/geometry\/init(line:)","type":"topic","title":"init(line:)","navigatorTitle":[{"text":"initWithLine:","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"line"},{"text":": [","kind":"text"},{"text":"NSValue","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSValue"},{"text":"])","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"initWithLine:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"- "},{"text":"initWithLine:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithLine:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSValue *>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"locations","kind":"internalParam"},{"kind":"text","text":";"}]}]}},{"value":"MBXGeometry","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Geometry\/title"},{"value":[{"text":"MBXGeometry","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Geometry\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Geometry\/navigatorTitle","value":[{"kind":"identifier","text":"MBXGeometry"}],"op":"replace"},{"value":"initWithLine:","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Geometry~1init(line:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithLine:"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Geometry~1init(line:)\/fragments"}]}]}