{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestOrResponse"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"modules":[{"name":"MapboxCommon"}],"symbolKind":"method","roleHeading":"Type Method","externalID":"c:objc(cs)MBXHttpRequestOrResponse(cm)fromHttpResponse:","navigatorTitle":[{"kind":"identifier","text":"fromHttpResponse:"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fromHttpResponse"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBXHttpResponse","kind":"typeIdentifier","text":"HttpResponse"},{"kind":"text","text":") -> "},{"text":"Self","kind":"typeIdentifier"}],"title":"fromHttpResponse(_:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fromHttpResponse"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"value"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpResponse","kind":"typeIdentifier","text":"HttpResponse","preciseIdentifier":"c:objc(cs)MBXHttpResponse"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Self"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/httprequestorresponse\/fromhttpresponse(_:)"]},{"paths":["\/documentation\/mapboxcommon\/httprequestorresponse\/fromhttpresponse(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestOrResponse\/fromHttpResponse(_:)"},"kind":"symbol","sections":[],"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","type":"topic","kind":"article","abstract":[],"url":"\/documentation\/overview","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequestOrResponse":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HttpRequestOrResponse"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestOrResponse","navigatorTitle":[{"kind":"identifier","text":"HttpRequestOrResponse"}],"title":"HttpRequestOrResponse","url":"\/documentation\/mapboxcommon\/httprequestorresponse","kind":"symbol","abstract":[{"type":"text","text":"Contains either an HttpRequest or an HttpResponse."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","title":"MapboxCommon","url":"\/documentation\/mapboxcommon","abstract":[],"role":"collection","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequestOrResponse/fromHttpResponse(_:)":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestOrResponse\/fromHttpResponse(_:)","role":"symbol","navigatorTitle":[{"text":"fromHttpResponse:","kind":"identifier"}],"kind":"symbol","abstract":[],"title":"fromHttpResponse(_:)","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fromHttpResponse"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"HttpResponse","preciseIdentifier":"c:objc(cs)MBXHttpResponse"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Self"}],"url":"\/documentation\/mapboxcommon\/httprequestorresponse\/fromhttpresponse(_:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpResponse":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"HttpResponse"}],"url":"\/documentation\/mapboxcommon\/httpresponse","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HttpResponse"}],"title":"HttpResponse","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpResponse","type":"topic","abstract":[{"type":"text","text":"Record which is used to report HTTP response to the caller."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"value":"fromHttpResponse:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"fromHttpResponse:"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"text":") ","kind":"text"},{"text":"fromHttpResponse:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MBXHttpResponse","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXHttpResponse","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpResponse"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"value"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"MBXHttpRequestOrResponse","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestOrResponse\/title"},{"op":"replace","value":[{"text":"MBXHttpRequestOrResponse","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestOrResponse\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestOrResponse\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBXHttpRequestOrResponse"}]},{"op":"replace","value":"fromHttpResponse:","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestOrResponse~1fromHttpResponse(_:)\/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"fromHttpResponse:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestOrResponse~1fromHttpResponse(_:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpResponse\/title","value":"MBXHttpResponse","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MBXHttpResponse"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpResponse\/fragments"},{"value":[{"kind":"identifier","text":"MBXHttpResponse"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpResponse\/navigatorTitle"}]}]}