{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoaded"]]},"metadata":{"externalID":"c:objc(cs)MBMSourceDataLoaded(py)type","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"type"},{"text":": ","kind":"text"},{"text":"SourceDataLoadedType","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMSourceDataLoadedType"}],"navigatorTitle":[{"kind":"identifier","text":"type"}],"role":"symbol","symbolKind":"property","title":"type","modules":[{"name":"MapboxMaps"}],"roleHeading":"Instance Property"},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"The type of a loaded data."}],"kind":"symbol","identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoaded\/type","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@MBMSourceDataLoadedType","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoadedType","text":"SourceDataLoadedType"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/sourcedataloaded\/type"]},{"paths":["\/documentation\/mapboxmaps\/sourcedataloaded\/type"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceDataLoadedType":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SourceDataLoadedType"}],"title":"SourceDataLoadedType","abstract":[{"text":"The enumeration defines the type of loaded source data.","type":"text"}],"navigatorTitle":[{"text":"SourceDataLoadedType","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoadedType","type":"topic","url":"\/documentation\/mapboxmaps\/sourcedataloadedtype","kind":"symbol","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Events":{"title":"Map events","type":"topic","role":"collectionGroup","url":"\/documentation\/mapboxmaps\/events","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Events","kind":"article","abstract":[{"type":"text","text":"The simplified diagram of the events emitted by the map is displayed below."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"kind":"symbol","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}],"title":"MapboxMaps","type":"topic","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceDataLoaded/type":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"type","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SourceDataLoadedType","preciseIdentifier":"c:@E@MBMSourceDataLoadedType"}],"type":"topic","title":"type","navigatorTitle":[{"kind":"identifier","text":"type"}],"kind":"symbol","url":"\/documentation\/mapboxmaps\/sourcedataloaded\/type","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoaded\/type","abstract":[{"text":"The type of a loaded data.","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceDataLoaded":{"abstract":[{"text":"The ","type":"text"},{"code":"SourceDataLoaded","type":"codeVoice"},{"type":"text","text":" event is emitted when source data is loaded."}],"kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/sourcedataloaded","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoaded","role":"symbol","title":"SourceDataLoaded","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SourceDataLoaded","kind":"identifier"}],"navigatorTitle":[{"text":"SourceDataLoaded","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","type":"topic","kind":"article","abstract":[],"url":"\/documentation\/overview","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"type"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"type","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@E@MBMSourceDataLoadedType","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceDataLoadedType","kind":"typeIdentifier","text":"MBMSourceDataLoadedType"},{"text":" ","kind":"text"},{"kind":"identifier","text":"type"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoadedType\/title","value":"MBMSourceDataLoadedType"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoadedType\/fragments","value":[{"kind":"identifier","text":"MBMSourceDataLoadedType"}],"op":"replace"},{"value":[{"text":"MBMSourceDataLoadedType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoadedType\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoaded~1type\/title","value":"type"},{"value":[{"text":"type","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoaded~1type\/fragments"},{"value":"MBMSourceDataLoaded","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoaded\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoaded\/fragments","value":[{"kind":"identifier","text":"MBMSourceDataLoaded"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1SourceDataLoaded\/navigatorTitle","value":[{"text":"MBMSourceDataLoaded","kind":"identifier"}]}]}]}